[project]
name = "sauna-booking-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "selenium>=4.0.0",
    "python-dotenv>=1.0.0",
    "requests>=2.32.5",
]
